version: 2
jobs:
  build:
    working_directory: /tmp/wordpress/
    docker:
      - image: circleci/php:5.6.37-node-browsers
        environment:
          WP_TESTS_DIR: /tmp/wordpress-tests-lib
          WP_CORE_DIR: /tmp/wordpress/
      - image: circleci/mysql:5.6
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: ubuntu
          
    steps:
      - checkout
      - run: 
          name: Update
          command: sudo apt-get update; sudo apt-get install -y subversion mysql-client
      - run: composer install
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: composer phpcbf
      - run: composer phpcbf-tests
      - run: composer phpcs-tests
      - run: composer compat
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run: |
          bash bin/install-wp-tests.sh wordpress_test ubuntu '' 127.0.0.1 latest
          composer test
      - run: |
          rm -rf $WP_TESTS_DIR $WP_CORE_DIR
          bash bin/install-wp-tests.sh wordpress_test ubuntu '' 127.0.0.1 trunk
          composer test
      - run: |
          phpenv global 5.3.29
          rm -rf $WP_TESTS_DIR $WP_CORE_DIR
          bash bin/install-wp-tests.sh wordpress_test ubuntu '' 127.0.0.1 latest
          composer test
      - run: |
          phpenv global 7.1.9
          rm -rf $WP_TESTS_DIR $WP_CORE_DIR
          bash bin/install-wp-tests.sh wordpress_test ubuntu '' 127.0.0.1 latest
          composer test

